Repository SchBenedikt/schbenedikt.github.io, pull requests merged in 2023-07, with the labels that each got.

#8 feat: cleanup HTML file
  index.html
  script.js
  style.css
Labels: suggestion

#10 2023.07.21
  index.html
  project.html
  script.js
  style.css
Labels: suggestion

#15 Feat prediction
  index.html
  js/predict.js
  js/script.js
  style.css
Labels: suggestion

#21 Fixed the Home Button
  index.html
  js/script.js
Labels: bug, suggestion

#20 Update project.html
  project.html
Labels: bug, suggestion

#23 Project card performance improved
  js/script.js
Labels: feature change
